# Buildpack API version
api = "0.2"

# Buildpack ID and metadata
[buildpack]
id = "io.fly.deno"
version = "0.0.1"
name = "Deno Buildpack"

# Stacks that the buildpack will work with
[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs3"

[[stacks]]
id = "org.cloudfoundry.stacks.bionic"
